# Generated by Django 4.1.5 on 2023-01-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedCommandsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('comment', models.CharField(max_length=150)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ManyToManyField(blank=True, related_name='sender', to='admins.admin')),
            ],
        ),
    ]
