# Generated by Django 4.1.5 on 2023-01-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_network',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
