# Generated by Django 4.1.5 on 2023-01-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_social_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='none', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
