# Generated by Django 4.0.6 on 2022-07-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('nickname', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sended_to', models.ManyToManyField(to='admins.admin')),
            ],
        ),
    ]
