# Generated by Django 4.0.5 on 2022-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_timestamp_admin_time_created_and_more'),
        ('warnings_', '0002_rename_time_warning_time_created_warning_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='sended_to',
            field=models.ManyToManyField(blank=True, related_name='sended_to', to='admins.admin'),
        ),
    ]
