# Generated by Django 4.0.5 on 2022-07-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings_', '0003_alter_warning_sended_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='sended_all',
            field=models.BooleanField(default=False),
        ),
    ]
