# Generated by Django 4.0.5 on 2022-07-26 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='timestamp',
            new_name='time_created',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='online',
        ),
        migrations.AddField(
            model_name='admin',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='server',
            field=models.CharField(default='185.169.134.83:7777', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='spectate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
